version: '2'

services:
  jira:
    image: eugenmayer/jira:en-${JIRA_VERSION}
    depends_on:
      - db
#    build:
#      context: ./
#      args:
#        JIRA_VERSION: ${JIRA_VERSION}
    container_name: jirasoftware
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@db/jiradb'
      #- 'JIRA_DATABASE_URL=mysql://jira@mysql/jiradb'
      # for mysql up to 5.6
      #- 'JIRA_MYSQL_DB_VERSION=mysql
      # for mysql from 5.7+=
      #- 'JIRA_MYSQL_DB_VERSION=mysql57
      - 'JIRA_DB_PASSWORD=jellyfish'
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
      - 'DOCKER_WAIT_HOST=db'
      - 'DOCKER_WAIT_PORT=5432'
      #- 'DOCKER_WAIT_HOST=mysql'
      #- 'DOCKER_WAIT_PORT=3306'

  db:
    image: postgres:10
    hostname: postgresql
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
# uncomment this to run against mysql
#  db:
#    image: mysql:5.7
#    hostname: mysql
#    volumes:
#      - mysqldata:/var/lib/mysql
#    environment:
#      - 'MYSQL_ROOT_PASSWORD=verybigsecretrootpassword'
#      - 'MYSQL_DATABASE=jiradb'
#      - 'MYSQL_USER=jira'
#      - 'MYSQL_PASSWORD=jellyfish'
volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false
  mysqldata:
    external: false
  newdb:
    external: false
