version: "3"

services:
  jira:
    image: eugenmayer/jira
    container_name: jira
    ports:
      - '80:8080'
    environment:
      JIRA_DATABASE_URL: mysql://jiradb@db/jiradb
      # since we run against mysql5.7 - below that set to mysql
      JIRA_MYSQL_DB_VERSION: mysql57
      JIRA_DB_PASSWORD: jellyfish
  db:
    image: mysql:5.7
    environment:
      - 'MYSQL_ROOT_PASSWORD=verybigsecretrootpassword'
      - 'MYSQL_DATABASE=jiradb'
      - 'MYSQL_USER=jiradb'
      - 'MYSQL_PASSWORD=jellyfish'
